sonar.projectKey=ticket-infra
sonar.projectName=Ticket Infra
sonar.sources=.
sonar.exclusions=**/.terraform/**,**/*.tfstate,**/*.tfstate.*,dependency-check-report/**,trivy-results.sarif
sonar.sourceEncoding=UTF-8
