grafana:
  enabled: true
  defaultDashboardsTimezone: Asia/Ho_Chi_Minh
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
  additionalDataSources:
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc.cluster.local:3200
      jsonData:
        tracesToLogsV2:
          datasourceUid: prometheus
        serviceMap:
          datasourceUid: prometheus
  persistence:
    enabled: true
    size: 5Gi
  ingress:
    enabled: true
    ingressClassName: alb
    hosts:
      - grafana.ticketstage.example.com

prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: 20GB
    serviceMonitorSelector:
      matchLabels:
        release: kube-prometheus-stack
    serviceMonitorNamespaceSelector: {}
    ruleSelector:
      matchLabels:
        release: kube-prometheus-stack
    ruleNamespaceSelector: {}
    scrapeInterval: 30s
    evaluationInterval: 30s
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 2
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: alertmanager
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  admissionWebhooks:
    enabled: true
