tempo:
  retention: 24h

nodeSelector:
  workload: system-pods

tolerations:
  - key: system
    operator: Equal
    value: "true"
    effect: NoSchedule

persistence:
  enabled: true
  storageClassName: ticketstage-gp3
  size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
