apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - backend-microservices.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress-aws-alb.yaml
