apiVersion: v1
kind: Secret
metadata:
  name: ticketstage-secrets
  namespace: ticketstage
type: Opaque
stringData:
  JWT_SECRET: "replace_me"
  INTERNAL_API_KEY: "replace_me"
  SECRET_HASH_KEY: "replace_me"
  PASSWORD_PEPPER: "replace_me"
  PASSWORD_HASH_ROUNDS: "12"
  MIN_PASSWORD_LENGTH: "8"
  AUTH_MONGODB_URI: "mongodb+srv://replace_me/ticket-auth"
  CATALOG_MONGODB_URI: "mongodb+srv://replace_me/ticket-catalog"
  BOOKING_MONGODB_URI: "mongodb+srv://replace_me/ticket-booking"
  CHECKIN_MONGODB_URI: "mongodb+srv://replace_me/ticket-checkin"
  NOTIFICATION_MONGODB_URI: "mongodb+srv://replace_me/ticket-notification"
  EVENT_BROKER_URL: "amqp://rabbitmq.ticketstage.svc.cluster.local:5672"
  VNPAY_TMN_CODE: "replace_me"
  VNPAY_HASH_SECRET: "replace_me"
  VNPAY_PAYMENT_URL: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  VNPAY_RETURN_URL: "https://api.ticketstage.example.com/api/payment/return/vnpay"
  VNPAY_IPN_URL: "https://api.ticketstage.example.com/api/payment/webhooks/vnpay"
  MOMO_ENDPOINT: "https://test-payment.momo.vn/v2/gateway/api/create"
  MOMO_PARTNER_CODE: "replace_me"
  MOMO_ACCESS_KEY: "replace_me"
  MOMO_SECRET_KEY: "replace_me"
  MOMO_REDIRECT_URL: "https://www.ticketstage.example.com/payment/result"
  MOMO_IPN_URL: "https://api.ticketstage.example.com/api/payment/webhooks/momo"
  MOMO_REQUEST_TYPE: "captureWallet"
  EMAIL_HOST: "email-smtp.us-east-1.amazonaws.com"
  EMAIL_USER: "replace_me"
  EMAIL_PASS: "replace_me"
  SES_SMTP_HOST: "email-smtp.us-east-1.amazonaws.com"
  SES_SMTP_PORT: "587"
  SES_SMTP_USERNAME: "replace_me"
  SES_SMTP_PASSWORD: "replace_me"
