apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: ticketstage
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: ticketstage
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: ticketstage
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: ticketstage
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-service
  namespace: ticketstage
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: ticketstage
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: booking-service
  namespace: ticketstage
  labels:
    app.kubernetes.io/name: booking-service
    app.kubernetes.io/part-of: ticketstage
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkin-service
  namespace: ticketstage
  labels:
    app.kubernetes.io/name: checkin-service
    app.kubernetes.io/part-of: ticketstage
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: ticketstage
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: ticketstage
automountServiceAccountToken: false
