apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticketstage-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: ticketstage
    app.kubernetes.io/part-of: ticketstage
    environment: prod
spec:
  project: ticketstage
  source:
    repoURL: https://github.com/PlatypusInAHat/ticket-infra
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ticketstage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
  revisionHistoryLimit: 10
