apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ticketstage-api-gateway
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ticketstage-api-gateway
    newTag: 0.0.0-placeholder
  - name: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ticketstage-auth-service
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ticketstage-auth-service
    newTag: 0.0.0-placeholder
  - name: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ticketstage-catalog-service
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ticketstage-catalog-service
    newTag: 0.0.0-placeholder
  - name: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ticketstage-booking-service
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ticketstage-booking-service
    newTag: 0.0.0-placeholder
  - name: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ticketstage-checkin-service
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ticketstage-checkin-service
    newTag: 0.0.0-placeholder
  - name: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ticketstage-notification-service
    newName: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/ticketstage-notification-service
    newTag: 0.0.0-placeholder

patches:
  - target:
      kind: ConfigMap
      name: ticketstage-config
    patch: |-
      - op: replace
        path: /data/FRONTEND_URL
        value: https://staging.ticketstage.example.com
      - op: replace
        path: /data/PUBLIC_API_URL
        value: https://api-staging.ticketstage.example.com
  - target:
      kind: ConfigMap
      name: ticketstage-observability-config
    patch: |-
      - op: replace
        path: /data/OTEL_RESOURCE_ATTRIBUTES
        value: service.namespace=ticketstage,deployment.environment=staging
  - target:
      kind: Ingress
      name: ticketstage-api
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api-staging.ticketstage.example.com
